version: '3.8'

services:
  env:
    container_name: dev-env 
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
    volumes:
      - C:\Programming:/root/workspace
      - .\nvim:/root/.config/nvim
      - .\dotfiles:/root/dotfiles
      - .\init:/root/init
      - /var/run/docker.sock:/var/run/docker.sock